language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencie
before_install:
  - openssl aes-256-cbc -K $encrypted_ea898f73cf4d_key -iv $encrypted_ea898f73cf4d_iv -in pytest.ini.enc -out pytest.ini -d
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - make test
